name: promoted -> main

on:
  push:
    branches:
      - promoted

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Merge promoted -> main
        uses: everlytic/branch-merge@master
        with:
          target_branch: main
